"""Backend for IBM Load Sharing Facility (LSF).

To use this backend, you must activate the `lsf` backend. This backend requires
the commands `bsub` and `bjobs`.

**Backend options:**

None.

**Target options:**

* **cores (int):**
    Number of cores allocated to this target (default: 1).
* **memory (str):**
    Memory allocated to this target (default: 4GB).
* **queue (str):**
    Queue to submit the target to (default: normal).
    for different purposes or priorities.
* **tokens [str,int]:**
    Name and number of LSF resource tokens to request (default: unset). If supplied 
    adds `token_name>=token_num` to `-R` strings.

"""

import os
import re
import logging

import attrs

from ..utils import ensure_trailing_newline
from .base import BackendStatus, TrackingBackend
from .utils import call, has_exe

logger = logging.getLogger(__name__)

TARGET_DEFAULTS = {
    "queue": "normal",
    "memory": "4GB",
    "cores": 1,
    "tokens": None
}

BJOB_STATES = {
    "PEND": BackendStatus.SUBMITTED,
    "WAIT": BackendStatus.SUBMITTED,
    "RUN": BackendStatus.RUNNING,
    "ZOMBI": BackendStatus.RUNNING,
    "DONE": BackendStatus.COMPLETED,
    "EXIT": BackendStatus.FAILED,
    "PSUSP": BackendStatus.FAILED,
    "USUSP": BackendStatus.FAILED,
    "SSUSP": BackendStatus.FAILED,
    "UNKWN": BackendStatus.UNKNOWN,
}


@attrs.define
class LSFOps:
    working_dir: str = attrs.field()
    target_defaults: dict = attrs.field()

    def cancel_job(self, job_id):
        logger.debug(f"Cancelling job {job_id}")
        call("bkill", job_id)

    def submit_target(self, target, dependencies):
        script = self.compile_script(target)
        with open(
            os.path.join(self.working_dir, ".gwf", "logs", target.name + ".sh"), "w"
        ) as f:
            f.write(script)
        args = []
        if dependencies:
            args.append("-w")
            args.append(" && ".join([f"done({job_id})" for job_id in dependencies]))
            args.append("-ti")
        logger.debug(f"Submitting job {target.name} to LSF")
        stdout = call("bsub", *args, input=script).strip()
        job_id = re.search(r"Job <(\d+)>", stdout)[1]
        return job_id

    def get_job_states(self, tracked_jobs):
        logger.debug("Getting job states from LSF")
        if not tracked_jobs:
            return {}
        # Default tracked job IDs to UNKNOWN
        job_states = {job_id: BackendStatus.UNKNOWN for job_id in tracked_jobs}

        # Get all current job statuses
        for line in call("bjobs", "-noheader", "-o" , "jobid stat delimiter=','").splitlines():
            job_id, state = line.strip().split(",")
            # Update job status if tracked
            if job_id in tracked_jobs:
                job_states[job_id] = BJOB_STATES[state]
        return job_states

    def compile_script(self, target):
        target_options = target.options
        stderr_path = os.path.join(
            self.working_dir, ".gwf", "logs", target.name + ".stderr"
        )
        stdout_path = os.path.join(
            self.working_dir, ".gwf", "logs", target.name + ".stdout"
        )
        memory = target_options["memory"]
        cores = target_options["cores"]
        queue = target_options["queue"]
        
        # Get any token_* options and convert to token_name,number
        out = []
        out.append("#!/bin/bash")
        out.append(f"#BSUB -M {memory}")
        # Build resource select and rusage lines - need to know what tokens to request, if any
        tokens = target_options.get("tokens", None)
        if tokens:
            token_name, num_tokens = tokens
            token_select = f" && {token_name}>={num_tokens}"
            token_rusage = f" && {token_name}={num_tokens}"
        else:
            token_select = ""
            token_rusage = ""
        out.append(f"#BSUB -R 'select[mem>{memory}{token_select}] span[hosts=1]'")
        out.append(f"#BSUB -R 'rusage[mem={memory}{token_rusage}]'")
        out.append(f"#BSUB -n {cores}")
        out.append(f"#BSUB -q {queue}")
        out.append(f"#BSUB -oo {stdout_path}")
        out.append(f"#BSUB -eo {stderr_path}")
        out.append(f"#BSUB -J {target.name}")
        out.append("# Generated by: gwf")
        out.append("")
        out.append("cd {}".format(target.working_dir))
        out.append("set -e")
        out.append("")
        out.append(ensure_trailing_newline(target.spec))

        return "\n".join(out)

    def close(self):
        pass


def create_backend(working_dir):
    return TrackingBackend(
        working_dir,
        name="lsf",
        ops=LSFOps(working_dir, target_defaults=TARGET_DEFAULTS),
    )


def priority():
    if has_exe("bsub"):
        return 100
    return -100


setup = (create_backend, priority())
